services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    ports:
      - "3000:3000"
    environment:
      - IMMICH_URL=http://your-internal-immich-server:2283
    healthcheck:
      test: wget -q --connect-timeout=10 --tries=1 --spider http://localhost:3000/share/healthcheck || exit 1
      start_period: 10s
      timeout: 5s
